### ISSUE TITLE
Only one usage of each socket errror

### ISSUE THREAD

**Issue by jasvi** [CodeBardian/tplink-smartdevices-netstandard#1]
Using Win10, VS2019, Net 4.8, I created a simple form and tried you example to discover devices. I downloaded the most current version and receive the following error when I execute. I have verified using tcpview.exe that no other process is using that local port.  I would appreciate any advice on how I can resolve it?

System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by jasvi** [comment]
I realized I this is for net standard 1.6.
Apologies.

**Comment by CodeBardian** [comment]
well it is .net standard but it should still be working if you reference it from .net 4.8. But you were right about the issue, i tried to reproduce and got the same error. In the latest version it should now be fixed.
