### ISSUE TITLE
Can you publish the latest version to NuGet gallery?

### ISSUE THREAD

**Issue by doggy8088** [CodeBardian/tplink-smartdevices-netstandard#21]
The dependency of the Newtonsoft.Json seems outdated. The latest version of Json.NET should be `13.0.1`.

![image](https://user-images.githubusercontent.com/88981/181075904-a896cf5a-9ef5-4a4e-8a0e-2232cdf4a2a4.png)

**Comment by CodeBardian** [comment]
Sorry I forgot to do that. I will take care of it in a couple of days.

**Comment by doggy8088** [comment]
@CodeBardian You can setup CI/CD for the NuGet package publishing someday. 😃 

https://github.com/marketplace/actions/publish-nuget
