### ISSUE TITLE
Add transition_period to TPLinkBulb.SetPoweredOn method

### ISSUE THREAD

**Issue by oversizedcanoe** [CodeBardian/tplink-smartdevices-netstandard#24]
Currently, the `SetBrightness`/`SetColorTemp`/`SetHSV` methods in the `TPLinkBulb` class all have an optional parameter for `transition_period`. The only one missing one is the `SetPoweredOn` method. 

For my use case, this means I can't quickly turn on/off the bulbs (KL125 (US) model) as there seems to be a built in transition period. I think providing the user this option is beneficial.

I have forked this repo [to my own profile](https://github.com/oversizedcanoe/tplink-smartdevices-netstandard), implemented this change by removing the `abstract` and `override` modifiers on the `TPLinkSmartDevice.SetPoweredOn(...)` methods, and providing an optional transition period to the `TPLinkBulb` class just like the other methods do, and it seems to work smoothly.

I have never made a PR to an open source repo, so I'm not sure if I'm supposed to just make a PR and cross my fingers, or wait for feedback on implementation from the maintainers. Let me know.

**Comment by CodeBardian** [comment]
You are of course very welcome to provide a pull request. However I am not to sure if I would be completely happy with the changes you did.

Removing the abstract `SetPoweredOn` method somewhat defeats the purpose of having that abstract base class at all. 
I would maybe rather add an overload that accepts the transition period in the bulb class.

```cs
public async Task SetPoweredOn(bool value, int transition_period)
{
    await Execute("smartlife.iot.smartbulb.lightingservice", "transition_light_state", new JObject
    {
        new JProperty("on_off", value ? 1 : 0),
        new JProperty("transition_period", transition_period)
    }, null).ConfigureAwait(false);
    _poweredOn = value;
}
```

and then keep the implementation of the abstract method as
```cs
public override async Task SetPoweredOn(bool value)
{
    await SetPoweredOn(value, 0);
}
```

**Comment by oversizedcanoe** [comment]
That definitely sounds like a better way. I'll make a pull request with that implementation.
